name: Deployment

on: [release]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Ballerina Build
      uses: ballerina-platform/ballerina-action/@1.1.1
      with:
        args: 
          build -a -c 
      env: 
        AZURE_CV_KEY: ${{ secrets.AZURE_CV_KEY }}
    - name: Ballerina Push
      uses: ballerina-platform/ballerina-action/@1.1.1
      with:
        args: 
          push -a
      env: 
        BALLERINA_CENTRAL_ACCESS_TOKEN: ${{ secrets.BALLERINA_CENTRAL_ACCESS_TOKEN }}
