name: CI

on: [release]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Ballerina Push
      uses: ballerina-platform/ballerina-action/@1.1.1
      with:
        env: 
          BALLERINA_CENTRAL_ACCESS_TOKEN = ${{ secrets.BALLERINA_CENTRAL_ACCESS_TOKEN	}}
        args: 
          push 
